### ISSUE TITLE
On EasyGrepReplaceWindowMode = 2 creates windows when replacing

### ISSUE THREAD

**Issue by saaguero** [dkprice/vim-easygrep#11]
According to documentation the following setting
```
let g:EasyGrepReplaceWindowMode = 2
```
Should be for cases where we don't want any window to be opened in the process of replacing; and it should automatically save all the changes. 

In my case it's behaving exactly the same as having no setting (meaning using the default 0)

However, if I test using a minimalistic vimrc (https://github.com/bling/minivimrc) it seems to do another thing... it replaces without opening any buffer but first it ask for confirmation (shouldn't just work directly?)... and also is not being auto save (should I activate some vim settings for this to happen?)

Any ideas?

**Comment by dkprice** [comment]
I took a look at the code but nothing is obvious to me. The relevant settings are 'switchbuf' and 'autowriteall'. I'm not aware of any other settings that would effect either of these. 

What version of vim are you using? What system are you running on?
