### ISSUE TITLE
<Leader>vv error

### ISSUE THREAD

**Issue by sweetdark** [dkprice/vim-easygrep#13]
Error detected while processing function <SNR>69_GrepCurrentWord..<SNR>69_DoGrep..<SNR>69_HasTargetsTahtMatch...
E118: Too many arguments for function : glob
E15: Invalid expression : glob(p,0,1)

E121: Undefined variable: fileList

vim version is 7.3   OS: win7

**Comment by dkprice** [comment]
What version of Vim are you using and what platform are you running on? 

The glob() function has three arguments; that's what the code is passing in. I can see from your error message that p is a '*', which is one of the valid wildcards to glob.

Can you experiment with calling glob() on your own to see why it's failing for you?

**Comment by vijayrudraraju** [comment]
I also get this error, just installed it. Version 7.3 on OSX yosemite

**Comment by dkprice** [comment]
I just defaulted the option that appears to be causing the problem to zero. Can you try again?
