### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by wikimatze** [dkprice/vim-easygrep#17]
Will there be one? I think you are going to make a first release with even more tested features.

**Comment by dkprice** [comment]
Yes, eventually. I've got a number of goals that I'd like to achieve before doing so. In the meantime I've been doing my work in an unstable branch but eventually that will be merged to the master and eventually tagged as a release.

**Comment by wikimatze** [comment]
I'm fine with this.

**Comment by wikimatze** [comment]
Hi there, I think the unstable branch is now ready, since it's behind from master by seven commits. Maybe now it's time for a release?

**Comment by wikimatze** [comment]
You dumped version 2.0 - think now it's time for a release tag.

**Comment by wikimatze** [comment]
Thanks for the release.
