### ISSUE TITLE
Default result filters

### ISSUE THREAD

**Issue by sergey-vlasov** [dkprice/vim-easygrep#18]
I would like to filter out binary files from results. Currently I use ```ResultListFilter -v Binary file``` but that has to be manually run after every ```<leader>vv```, ```:Grep``` and others. Would it be possible to add an option to define default filters?

**Comment by dkprice** [comment]
You have a couple of options here. If you are using vimgrep, you can use EasyGrepFilesToExclude to exclude them. EasyGrep also supports other grep programs that will skip over binary files by default; you might be interested in ack, ag, or pt.

**Comment by sergey-vlasov** [comment]
Indeed, I totally forgot that the standalone tools have options to ignore binary files.
