### ISSUE TITLE
Set grep program globally

### ISSUE THREAD

**Issue by faceleg** [dkprice/vim-easygrep#30]
Is there a way to (for example) set ack as my grep program without having to call GrepProgram each time I start vim? I'd like to be able to do this in my vimrc

**Comment by dkprice** [comment]
Set this in your .vimrc

    let g:EasyGrepCommand="ack"

**Comment by faceleg** [comment]
Ah, thank you!

**Comment by faceleg** [comment]
If I were to update the documentation, what section would you like this in?
