### ISSUE TITLE
EasyGrepRoot docs are incorrect for searching repositories

### ISSUE THREAD

**Issue by bdchauvette** [dkprice/vim-easygrep#31]
Great plugin!

I just ran into a bit of a speedbump configuring it to use repos as the root, though.

The [current docs](https://github.com/dkprice/vim-easygrep/blob/master/doc/EasyGrep.txt#L391) say that you can search through a repository by setting`EasyGrepRoot` to `repo`.

However, the actual setting is [`repository`](https://github.com/dkprice/vim-easygrep/blob/22e65eaa9635ffce24266e5be4c8ba1aa8398f2a/plugin/EasyGrep.vim#L182).

(This might be the issue with #28?)

**Comment by dkprice** [comment]
Thanks, I fixed the docs.
