### ISSUE TITLE
Unable to exclude directories

### ISSUE THREAD

**Issue by wjagodfrey** [dkprice/vim-easygrep#33]
I find EasyGrep a little hard to use for a couple of reasons - in most cases because (it seems) I'm unable to exclude directories. I'm a Node developer, so searching for any .js file recursively will immediately drop me into my huge node_modules directory - a great big time sink, and an unnecessary one.

Please add wildcard directory exclusions, or help me understand how to work around this issue.

**Comment by dkprice** [comment]
What is your configuration? Not all programs support exclusions -- in particular vimgrep doesn't.

**Comment by wjagodfrey** [comment]
Ah, that would explain it I guess. Vimgrep was the culprit.

**Comment by SantoshSrinivas79** [comment]
@dkprice can you please advise how to exclude directories like `node_modules` that @wjagodfrey mentioned? sorry, couldn't figure out from the documentation

**Comment by dkprice** [comment]
The setting is called EasyGrepFilesToExclude. You'd configure this setting like:

    e.g. let g:EasyGrepFilesToExclude=".svn,.git,node_modules"

**Comment by StrongBearCeo** [comment]
I am working on react-native project. I excluded certain files and folders

- folders: android, ios, node_modules, coverage, `__snapshots__`
- files: *.lock, *.log

By putting these lines in ~/.vimrc
```sh
let g:EasyGrepFilesToExclude='android,ios,node_modules,coverage,*.lock,*.log,__snapshots__'
let g:EasyGrepRecursive=1
let g:EasyGrepCommand=1   # important, otherwise, it won't work
```
It was not easy to find out, so I think it's worth to put a note here
