### ISSUE TITLE
Disable mapping completely

### ISSUE THREAD

**Issue by albertnetymk** [dkprice/vim-easygrep#37]
Even with https://github.com/dkprice/vim-easygrep/blob/master/doc/EasyGrep.txt#L510, some mappings are still introduced by this plugin https://github.com/dkprice/vim-easygrep/blob/master/plugin/EasyGrep.vim#L3372.

Is it possible to disable them as well?

**Comment by dkprice** [comment]
This is fixed in the master branch.

**Comment by jsborjesson** [comment]
From what I understand, this only disables *some* of the mappings, the ones that use this option prefix - but this plugin introduces quite a few more. It would be nice to have an option to disable all of the leader mappings
