### ISSUE TITLE
Is it possible to search only the current buffer

### ISSUE THREAD

**Issue by HRonald85** [dkprice/vim-easygrep#38]
Hello , thank you for making an awesome plugin. This plugin is definitely a productivity booster. I wanted to know if it is possible to search only the buffer you are in ? Also if it is possible to specify a path to search in like  `:Grep /search/this/path word `. Any feedback on this would be great. Again thank you for giving us a great plugin.

**Comment by fsworld009** [comment]
According to the document, there is no "Current buffer" mode as of now, only "Open buffers". I would love to see this feature get implemented, too.

**Comment by zedan185** [comment]
Yeah I realized that. That is why i am no longer using this plugin and am using ack . Simple and very effective.

**Comment by dkprice** [comment]
Added `g:EasyGrepSearchCurrentBufferOnly`  in commit 106b39f0cca0cb98d3c35a83ed6db48bb38c6081 . To use it set:

`let g:EasyGrepMode = 1`
`let g:EasyGrepSearchCurrentBufferOnly = 1`
