### ISSUE TITLE
Do I have to open all the files that I want to search and replace?

### ISSUE THREAD

**Issue by noscripter** [dkprice/vim-easygrep#40]
Do I have to put all the files in buffer before I can search and replace a pattern?

Right now if I just open a folder(which by default is handled by nerdtree) and use `:Grep`, these prompts keep jumping out:

![image](https://cloud.githubusercontent.com/assets/1673877/18656353/fdb1a15c-7f22-11e6-9acc-f400d25d12d6.png)

**Comment by dkprice** [comment]
Can you report what you get when you type this? <leader>vyv

That shows the shell command that EasyGrep uses. If the shell command is incorrect please let me know.

**Comment by Lornz-** [comment]
Hi there! I got the same question.

Here's the output after I type `<leader>vyv`:

```
[EasyGrep] Search Mode:           All
[EasyGrep] Search Directory:      /Users/lornz/apps
[EasyGrep] VIM command:           vimgrep /<pattern>/ *
Press ENTER or type command to continue
```

And here's what I got in my `~/.vimrc`:

```
let g:EasyGrepRoot = "repository"
let g:EasyGrepSearchCurrentBufferDir = 0
```

I don't want to search just in the current buffer. I want to be able to do it in all my search directory I set. What am I doing wrong here?

**Comment by dkprice** [comment]
If you're using vimgrep (a decent out-of-the-box tool but very slow) you'd need to turn on recursive mode because vimgrep is not inherently recursive.

`let g:EasyGrepRecursive=1`

These days I personally most often use ripgrep, though, a tool that is inherently recursive and super fast.
