### ISSUE TITLE
Any way to search specific subdirectories?

### ISSUE THREAD

**Issue by jpmv27** [dkprice/vim-easygrep#42]
I would like to search specific subdirectories under cwd (e.g., 'src', 'include') and exclude others (e.g., 'bin', 'doc', etc.)

Is there any way to configure easygrep to do that?

MV

**Comment by dkprice** [comment]
Try setting some exclusions. See EasyGrepFilesToExclude. This is only currently supported for grep, ack, and ag.

**Comment by jpmv27** [comment]
I would've preferred a "positive" vs. a "negative" selection (search this vs. don't search that,) but I'll give that option a try

Thanks
MV
