### ISSUE TITLE
Have to manually refresh (^L) after Grep with no matches

### ISSUE THREAD

**Issue by jpmv27** [dkprice/vim-easygrep#45]
Only happens on console vim, gvim is OK

After entering the Grep command, the screen is cleared, there are four
lines of "[EasyGrep] Warning:", followed by "Press ENTER or type command to continue"

After pressing enter, only three lines from the buffer are redrawn at the top of the
screen, the rest is blank. Restored to normal by ^L or :redraw! but NOT :redraw

Fixed by changing redraw to redraw! at line 2850 of plugin/EasyGrep.vim

I don't understand why all the redraws are required, so I'm unsure whether that is a reasonable fix.

**Comment by dkprice** [comment]
redraw is a big hammer but it seems appropriate. Thanks for fixing!
