### ISSUE TITLE
MultiSelect mode doesn't work recursively

### ISSUE THREAD

**Issue by jpmv27** [dkprice/vim-easygrep#65]
I am using grep as grepprg

When using TrackExt or User mode, the file patterns are wrapped using opt_str_mapinclusionsexpression (--include)

But when using MultiSelect mode, the file patterns are inserted into the command line without wrapping. As a result, recursive searches don't work properly

Is that intentional or a bug? If it's a bug, I'll try to submit a PR

My proposed fix would be to change IsModeFiltered to
```
    call s:SanitizeMode()
    return s:IsModeTracked() || s:IsModeUser() || s:IsModeMultipleChoice()
```

**Comment by dkprice** [comment]
Thanks for the fix! It has the same spirit as the existing code and as such I think its the right one.
