### ISSUE TITLE
[EasyGrep] Warning: Replace interrupted: Exception encountered: Vim(substitute):E488: Trailing characters

### ISSUE THREAD

**Issue by wikimatze** [dkprice/vim-easygrep#8]
I get this error when I edit the file https://github.com/wikimatze/wikimatze.de/blob/master/index.md and place the cursor on "wikimatze" in visual mode and then press `vr` to replace it with some other word.  Can you reproduce this error?

**Comment by dkprice** [comment]
I recently noticed a bug where the EscapeSpecialCharacters function was configured to unconditionally escape according to the grepprg in use; this however was incorrect for when it was being used to substitute given that vim required escaping that may not have been equivalent to the grepprg escaping. That was the likely issue; without a response I cannot verify. This fix is committed to the unstable branch.

**Comment by wikimatze** [comment]
Thanks, I will try it out.

**Comment by wikimatze** [comment]
The error has gone and it is working much faster and has better highlighting - thank you so much for working on this.
